apiVersion: v1
kind: Service
metadata:
  name: login-app-service
  labels:
    name: login-app-service
    app: login-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    name: login-app-pod
    app: login-app