apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app-deploy
  labels:
    name: login-app-deploy
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: login-app-pod
      app: login-app
  template:
    metadata:
      name: login-app-pod
      labels:
        name: login-app-pod
        app: login-app
    spec:
      containers:
        - name: login-app
          image: darshanadsw/login-app:v1
          ports:
            - containerPort: 8080
