apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: login-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: login-app
    spec:
      containers:
        - name: postgres-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: testdb
